### PR TITLE
Block Inspection

### LINKED ISSUE #3: Ability to identify murderer/sheriff using inspect
Players can identify the murderer/sheriff by inspecting their loadout, and whether they have a gun/knife.

### PR DESCRIPTION
**Pull request by rumblefrog**
Fixes #3

### CODE REVIEW

**Comment by keybangz** [comment]
I thought the inspect hook didn't work?

**Comment by rumblefrog** [comment]
@BloodTigerNZ Why wouldn't it? It's a console command, no?

**Comment by keybangz** [comment]
Yeah, but last time I tried it didn't work since it was fully client only, me and pancake already tried doing this. I mean unless somethings changed, I also recommend you clean up the code by changing INVALID_HANDLE to null

**Comment by rumblefrog** [comment]
@BloodTigerNZ null is not part of the handle enum

**Comment by Akke** [comment]
It's not possible I'm afraid, tried this in the very beginning of the development.

**Comment by rumblefrog** [comment]
I'll ask around, surely there's a workaround.

**Comment by rumblefrog** [comment]
@SirPurpleness Try this commit?

**Comment by Akke** [comment]
Already tried as well, doesn't work.

**Comment by keybangz** [comment]
I'll put it to you in a simple way, You can't. 
It's a full client thing, Best you could do is the hide the hud entirely.

**Comment by rumblefrog** [comment]
That's unfortunate, sorry for wasting time here

**Comment by rumblefrog** [comment]
FYI, Benoist suggest that you set the netprop "m_iEntityQuality" on the weapon to 0, it will block the wep from being inspected by alive players, dead players/spectators will still be able to inspect the wep. But I haven't gotten around to try this.

**Pull request closed without merging**
